---
- name: Set ipv4 forwarding
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward=1'
- name: Set NAT forwarding
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth1
    jump: MASQUERADE
- name: Forward eth0 to eth1
  iptables:
    chain: FORWARD
    in_interface: eth1
    out_interface: eth0
    match: conntrack
    ctstate: RELATED,ESTABLISHED
    jump: ACCEPT
- name: Forward eth0 to eth1
  iptables:
    chain: FORWARD
    in_interface: eth0
    out_interface: eth1
    jump: ACCEPT
- name: Save iptables rules
  shell: 'iptables-save > /etc/iptables.ipv4.nat'
- name: Create iptables file
  file:
    path: /etc/network/if-up.d/iptables
    state: touch
    mode: u=rwx,g=rx,o=rx
- name: Add iptables rules on restart
  lineinfile:
    path: /etc/network/interfaces
    line: 'up iptables-restore < /etc/iptables.ipv4.nat'
    state: present
