---
- hosts: localhost
  connection: local
  user: pirate
  become: yes
  tags:
  - dc
  - dns
  - gateway
  roles:
  - { role: dnsmasq, tags: ['dns','networking','dhcp'] }
  - gateway
  - { role: udev, tags: ['fs','external'] }

