---
- name: Install NFS Server
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - nfs-kernel-server
- name: Make Shares
  file:
    path: "{{ item }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 777
  with_items:
  - /media/Backup/shares
  - /media/Backup/shares/backup
- name: Add Share to exports file
  lineinfile:
    path: /etc/exports
    line: "{{ item.path }}   {{ item.perms }}"
  with_items:
  - { path: '/media/Backup/shares', perms: '192.168.50.0/24(rw,sync,no_subtree_check)' }
  - { path: '/media/Backup/shares/backup', perms: '192.168.50.0/24(rw,sync,no_subtree_check)' }
  - { path: '/home', perms: '192.168.50.0/24(rw,sync,no_root_squash,no_subtree_check)' }
  notify:
  - restart nfs-server
