---
- name: '[docker] Install Docker apt key'
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present
- name: '[docker] Add docker to apt sources
  lineinfile:
    line: deb https://download.docker.com/linux/raspbian stretch main
    state: present
    path: /etc/apt/sources.list.d/docker.list
- name: '[docker] Remove outdated docker from apt sources
  lineinfile:
    line: deb [arch=armhf] https://apt.dockerproject.org/repo raspbian-jessie main
    state: absent
    path: /etc/apt/sources.list.d/docker.list
- name: '[kubernetes] Register Kubernetes apt key'
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: '[kubernetes] Make sure kubernetes sources file exists'
  file:
    state: touch
    path: /etc/apt/sources.list.d/kubernetes.list
- name: '[kubernetes] Add Kubernetes to apt sources'
  lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: present
    line: deb http://apt.kubernetes.io kubernetes-xenial main
- name: '[kubernetes] Install Kubernetes'
  apt:
    name: kubeadm
    state: present
    update_cache: yes