---
- name: Generate SSH key
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
    ssh_key_file: "/home/{{ ansible_user }}/.ssh/id_rsa"
- name: Add key to authorized hosts
  authorized_key:
    user: pirate
    state: present
    key: "{{ lookup('file', '/home/{{ ansible_user }}/.ssh/id_rsa.pub') }}"
